### ISSUE TITLE
🛑 Service Orchestration is down

### ISSUE THREAD

**Issue by artbanx-monitoring** [artbanx-monitoring/status-page#18]
In [`629a480`](https://github.com/artbanx-monitoring/status-page/commit/629a4807f638f21893dad0aeea132542154e5163
), Service Orchestration (https://app.artbanx.io/health/offering/) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by tino-fernandez** [comment]
<img width="1512" alt="Screen Shot 2023-01-25 at 09 52 21" src="https://user-images.githubusercontent.com/101345155/214519776-e3a8f95c-db1f-4959-ba54-b738209ea912.png">
false positive, github actions are not working correctly
